name: file_sized
version: 2.0.0

description: Lightweight and intuitive package for file size conversions and human-readable formatting. Convert between bytes, kilobytes, megabytes, gigabytes, and terabytes. Easy to use utils.

repository: https://github.com/hossameldinmi/file_sized

screenshots:
  - description: The file_sized package logo.
    path: "assets/icon.png"

topics:
  - bytes
  - files
  - binary
  - storage
  - format

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  test: ^1.26.3
